name: Releases

on:
  workflow_dispatch:
  pull_request:
  push:

env:
  SOURCE_DIR:   ${{ github.workspace }}
  BUILD_TYPE:   ${{ fromJSON('["DailyBuild", "StableBuild"]')[ github.ref_type == 'tag' || contains(github.ref, 'Stable_' ) ] }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: 6.4.2
          host: linux
          target: desktop
          dir: ${{ runner.temp }}
          modules: qtcharts
          setup-python: true

      - name: Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --parallel --config Release

      - name: Install LinuxDeploy
        uses: miurahr/install-linuxdeploy-action@v1
        with:
          plugins: qt appimage

      - name: Create Appimage
        run: |
          # Install lib for linuxdeploy
          sudo apt install --yes libfuse2 libxkbcommon-x11-0
          export QML_SOURCES_PATHS=$PWD/qml
          linuxdeploy-x86_64.AppImage --desktop-file=deploy/qhot.desktop --executable=build/src/qhot --appdir=build/src --plugin=qt --output=appimage --verbosity=3 --icon-file=deploy/icon.png

      - name: Upload AppImage
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: qhot-*.AppImage
